### ISSUE TITLE
Please consider using ynh_install_extra_repo

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/jellyfin_ynh#1]
Hi

We noticed that you use an extra repository for your app. Using extra repository without pinning it can have consequences.
Please consider using the experimental helper [ynh_install_extra_repo](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_add_secure_repos/ynh_add_secure_repos__2) to handle securely any extra repo.

If you encounter any problem using this helper, please open an issue on the repo.

**Comment by liberodark** [comment]
how to use ?

**Comment by maniackcrudelis** [comment]
For your usage, have a look to the helper [ynh_install_extra_app_dependencies](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_add_secure_repos/ynh_add_secure_repos__3#L184)
This helper will add the repo you need, install the packages from this repo then remove the repo.
That way, you prevent any side effects with an extra repo.

**Comment by liberodark** [comment]
Fixed
