### ISSUE TITLE
Bug with trailers or individual database problem?

### ISSUE THREAD

**Issue by Schdefoon** [YunoHost-Apps/jellyfin_ynh#116]
Hi,

first I have to say that my installation is suspected to be corrupt. I had to uninstall Jellyfin 10.7.7 and do a fresh installation of 10.8.1. Because I don't wanted to lose all my data I manipulated the new generated database with many old values. This might be a problem in my installation ..

So far most things work very well. I only found one issue:
When I use the trailer icon in the movie overview it always starts a trailer from Youtube.
My movies are stored in the same folder like my trailers. So I have "My Movie.mp4" and "My Movie_trailer.mp4"

In Jellyfin 10.7.7 clicking on the trailer icon started my local trailer "My Movie_trailer.mp4"
Can somebody confirm that this is still working with 10.8.1?

**Comment by tituspijean** [comment]
`_trailer` looks to still be a valid suffix for filenames. https://jellyfin.org/docs/general/server/media/movies.html#file-suffix
Try force-regenerating your library. Since you hacked into your database in undisclosed ways, I suggest you should ask for support to Jellyfin people directly. ;)

**Comment by Schdefoon** [comment]
Thank you very much for helping.

A few days ago I have completely set up my Raspberry Pi with a fresh installation of Bullseye and a fresh installation of Jellyfin. I found out that local trailers are not supported when I use one folder with all movies and trailers in it. It seems that there is no difference if I use "My Movie_trailer.mp4" or "My Movie trailer.mp4" or "My Movie.trailer.mp4" or "My Movie-trailer.mp4". In each case the local trailer is ignored on my system.
What is working:
When I use a subfolder "My Movie (2020)" and put the files "My Movie (2020).mp4" and "trailer.mp4" in it, then the local trailer is recognized.
So I am reordering my movies as suggested 😊
