### ISSUE TITLE
Remote access to Jellyfin require ports 8096 and 8920 open

### ISSUE THREAD

**Issue by mateMathieu** [YunoHost-Apps/jellyfin_ynh#120]
### Describe the bug

It is impossible to access remotely jellyfin because HTTP/HTTPS traffic is going through ports that are not open by default.

### Context

- Hardware: *Homelab host on proxmox*
- YunoHost version: 11.0.10.1
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, package version: *10.8.5~ynh1*

### Steps to reproduce

- Install and configure Jellyfin on your server
- Install Jellyfin client on your friend's house TV
- Connect remotely from outside your network

### Messages
"Unable to connect to server, tried the following addresses:
- https://domain.example.com - SSL handshake failed
- https://domain.example.com:8096 - Unable to connect
- https://domain.example.com:8920 - Unable to connect
- http://domain.example.com - Unable to connect
- http://domain.example.com:8096 - Unable to connect

Changing the ports to 80 and 443 does not work and triggers a "502 Bad Gateway" on ngnix server.

### Expected behavior

Connect remotely and have ports 8096 and 8920 open on YNH admin panel.

### Info

The networking specification can be found here: https://jellyfin.org/docs/general/networking/index.html

**Comment by bettyvschmartz** [comment]
HTTP access over the Jellyfin client works fine for me, and the port was opened in the firewall when installing the app. In my case it was 8095. This only seems like a viable option over something like a wireguard VPN, otherwise it's completely insecure. You can check the port in `/etc/yunohost/apps/jellyfin/settings.yml`

I do have the issue however that using the Jellyfin client doesn't work using SSL. No port seems to be set for HTTPS or open in the firewall, even though as you linked to, the default port for Jellyfin is 8920. 

-- bvs

**Comment by mateMathieu** [comment]
Hi, thanks for your answer. It happens that jellyfin has somehow a messed up install or installation process.
When I opened the ports it required, it worked fine, but the diagnostic reports problems with some other ports that are not accessible and not configured.
These ports are 7359 and 1900. Is that normal? Should I open them as well?
Thanks

**Comment by kirbylife** [comment]
Ports 7359/udp and 1900/udp are required for jellyfin's autodiscovery function, you can leave them closed without any problems.
https://jellyfin.org/docs/general/networking/#static-ports

Currently I managed to connect to my instance from the applications by opening port 8095 and setting it explicitly at the time of connecting:
http:\//jellyfin.myinstance.xyz:**8095**
However, all the traffic goes through http, I have not been able to make it go through https without modifying the raw configuration.
