### ISSUE TITLE
502 Bad Gateway after install

### ISSUE THREAD

**Issue by ihaveimpulses** [YunoHost-Apps/jellyfin_ynh#122]
### Describe the bug

It loads to a 502 error. Here's the paste: I think it's database but I am new at this  stuff and don't know what this means or how to make it work https://paste.yunohost.org/melamaxoqu

### Context
- on the latest build
- AMD 5700G
- 15TB mechanical drive
- 128GB RAM
- regular at home using desktop

### Steps to reproduce

- install from the admin panel, load site, get error.

**Comment by stilobique** [comment]
Hi @ihaveimpulses 
I have solved my issue to replace the `migrationx.xml file`. [Look my issue](https://github.com/YunoHost-Apps/jellyfin_ynh/issues/112), maybe that can help you.

**Comment by ihaveimpulses** [comment]
now it just shuts the service down and it won't start up no matter what I try :(

Was worth a shot though, thanks

**Comment by stilobique** [comment]
Can you share your new log ?

**Comment by ihaveimpulses** [comment]
https://paste.yunohost.org/nulavoyapu

**Comment by stilobique** [comment]
Alright, no change with the log. Can you show this `/etc/jellyfin` folder with user access ? Use the command `ls -l`.

**Comment by tituspijean** [comment]
Closing, since it has been 9 months.
Sorry for the inconvenience, feel free to reopen if needed.
