### ISSUE TITLE
Support SSO

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/jellyfin_ynh#123]
I'm not sure how doable this is, but there is a plugin that might work to an extent:

https://github.com/9p4/jellyfin-plugin-sso/

It's probably not 100% ready (especially with apps), but worth keeping an eye on this.

Feature request: https://features.jellyfin.org/posts/230/support-for-oidc

**Comment by Salamandar** [comment]
SSO and OpenID are two very different things.

SSO should be supported by Jellyfin on Yunohost via the pre-installed LDAP plugin (I guess this one https://jellyfin.org/docs/general/server/plugins/#ldap). What that means is that you can connect with your yunohost credentials on Jellyfin.

The OpenID Connect though… It seems more tricky. The first step would be that Yunohost provides what's required for OpenID.

Nitpick: the issue should be named "Support OpenID Connect SSOs".

**Comment by Salamandar** [comment]
Ah, yes, i see what you mean, i made a mistake myself. It's not SSO, but more like centralized authentication. Being authentified in Yunohost does not make yourself autentified in Jellyfin automagically. You just have the same credentials.

Yunohost provides some kind of sso via a http header though. Maybe this could be used by Jellyfin.

**Comment by selfhoster1312** [comment]
> Yunohost provides some kind of sso via a http header though. Maybe this could be used by Jellyfin.

[Requested for a long time](https://features.jellyfin.org/posts/471/header-authentication), never implemented. I tried to do it myself last year but i don't know a lot of C# and Jellyfin authorization system is so complex, full of API keys and tokens for all endpoints (not binary user authorization/deny like a HTTP header does)... i could not do it.

**Comment by tituspijean** [comment]
Let's close for the time being, feel free to reopen if the situation evolves upstream.
