### ISSUE TITLE
Automatically set the administrator user

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/jellyfin_ynh#13]
As I was creating a password-less `jellyfin` account as administrator during the post-installation, I discovered I could not log back in this account afterwards.

It seems we can automatically set the admin by creating the directory `/etc/jellyfin/users/$admin` and the `policy.xml` file inside with the following contents:

```xml
<?xml version="1.0"?>
<UserPolicy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <IsAdministrator>true</IsAdministrator>
  <IsHidden>true</IsHidden>
  <IsDisabled>false</IsDisabled>
  <AuthenticationProviderId>Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin</AuthenticationProviderId>
</UserPolicy>
```

**Comment by liberodark** [comment]
Hi if you want make pr is ok but no change all just the need.
