### ISSUE TITLE
Installing Jellyfin install NVIDIA packages on a system with AMD GPU

### ISSUE THREAD

**Issue by axolrotflotl** [YunoHost-Apps/jellyfin_ynh#132]
### Describe the bug

*Installing the Jellyfin app, the installer mistakenly detected Nvidia hardware on my server and automatically installed drivers + kernel modules accordingly. For the record, my machine has an AMD GPU.*

*Unsurprisingly, now the computer throws warnings at boot about not finding the Nvidia hardware it's been set up for, and missing firmware for what it is actually equipped with.*

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 11.1.19 (stable)
- I have access to my server: *This installation was made through the web UI*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch:  10.8.10~ynh1

### Steps to reproduce
- In the webadmin panel, go to "Applications"
- Click "Install", search for "Jellyfin" with filter *Only decent quality apps*
- Click through to /yunohost/admin/#/apps/install/jellyfin
- Click "Install"
- Watch the error message counter tick past 40 as the installer fucks your firmware over.

### Expected behavior

*Install Jellyfin. The app does not rewrite my system. I can start using my new media server instead of having to repair my server setup at a kernel level.*

### Logs

*The logs disclose my admin username, and I'm not going to make that available online. See the edited logs at https://pastebin.com/3r35Ji6K*

**Comment by axolrotflotl** [comment]
A week later, I want to restate that an app currently labeled "decent quality* in the YNH catalog misidentified my hardware, installing drivers and kernel modules for a different GPU.

I would expect a swift response or even an acknowledgement from the package maintainers, but this silence is discouraging to say the least.

**Comment by Salamandar** [comment]
> The logs disclose my admin username, and I'm not going to make that available online. See the edited logs at https://pastebin.com/3r35Ji6K

Yunohost provides a tool that should remove such credentials.

I think you tried to install the Jellyfin package while your system was in a broken state. In the logs, you can see it starts trying to install the nvidia packages with this command:

```
apt-get --assume-yes --quiet -o=Acquire::Retries=3 -o=Dpkg::Use-Pty=0 --no-remove --option Dpkg::Options::=--force-confdef --option Dpkg::Options::=--force-confold install --fix-broken
```
There's no reference to Jellyfin here.

> I would expect a swift response or even an acknowledgement from the package maintainers, but this silence is discouraging to say the least.

We're all volunteers here, and the Jellyfin package is maintained by someone who's already managing a lot of packages.

**Comment by tituspijean** [comment]
Hello @axolrotflotl, sorry for the late reply and for my volunteering time not being compatible with your requirements.

Nothing in this package seemingly differentiates between AMD and NVIDIA hardware. If you can help me help you, can you install aptitude (`sudo apt install aptitude`) then run `sudo aptitude why <an nvidia package>` to understand which dependency is at fault.

**Comment by kay0u** [comment]
> I would expect a swift response or even an acknowledgement from the package maintainers, but this silence is discouraging to say the least.

And still no feedback... Yes, it's discouraging too for us
