### ISSUE TITLE
Automatic server discovery on LAN

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost-Apps/jellyfin_ynh#141]
Jellyfin supports automatic discovery via broadcast packages. However, it's currently broken (only returns LAN IP not exposed URL) until the next release, see https://github.com/jellyfin/jellyfin/issues/10005

However, when that bug is fixed and we can get the URL from broadcast, we should make sure we advertise the public address of the Jellyfin instance. I'm not sure exactly if that's supposed to use the `BaseUrl`, the `KnownProxies` or something else. I noticed in the admin interface a setting called "published server URIs" which could be it.

There's nothing we can do at this time i'm just posting this issue to keep the problem documented until it's magically fixed, or in case we actually need to change a setting after the next release to fix it.

**Comment by selfhoster1312** [comment]
Unfortunately https://github.com/jellyfin/jellyfin/issues/10005 did not fix the issue. I opened https://github.com/jellyfin/jellyfin/issues/11564 instead.

**Comment by kay0u** [comment]
Should be fixed by #158 feel free to reopen if you think it's not

**Comment by selfhoster1312** [comment]
Hopefully supported soon in Delfin: https://codeberg.org/avery42/delfin/pulls/137
