### ISSUE TITLE
Playback/transcoding doesn't work

### ISSUE THREAD

**Issue by ahstro** [YunoHost-Apps/jellyfin_ynh#152]
### Describe the bug

Most video content is unable to play, showing this "[Playback Error](https://github.com/YunoHost-Apps/jellyfin_ynh/assets/3090888/4d14e474-cadc-4163-b107-1084692b2ca4)". I'm fairly certain it's an issue with transcoding somehow, but unsure how to resolve? [The logs](https://paste.yunohost.org/ogupijawag) seem to indicate there's some permission shenanigans happening?
```bash
8:  Mar 11 22:59:38 jellyfin[852326]: [22:59:38] [ERR] [19] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/5fe00277-6dac-60a7-8e1e-e853aa63f273/hls1/main/0.ts.
9:  Mar 11 22:59:38 jellyfin[852326]: System.UnauthorizedAccessException: Access to the path '/var/log/jellyfin/FFmpeg.Transcode-2024-03-11_22-59-38_5fe002776dac60a78e1ee853aa63f273_c406036c.log' is denied.
```
The similar issues I found online suggested changing the ffmpeg path in the GUI. This has been disabled in this version, for [reasons](https://jellyfin.org/posts/jellyfin-security-and-you/), but I tried changing it by editing `/etc/jellyfin/encoding.xml` and restarting. Didn't help 🤷‍

### Context

- Hardware: Old computer with x86_64 architecture
- YunoHost version: `11.2.10.3` (stable)
- I have access to my server: Through SSH,  webadmin, and direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: I can't really open ports in my router, but that doesn't seem relevant? Although you never know..
- Using, or trying to install package version/branch: `10.8.13`

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. Go to web client
   2. Try to play a video
   3. Be sad

### Logs

https://paste.yunohost.org/ogupijawag

**Comment by stilobique** [comment]
Like the #150 ; force the reinstall with this command
```bash
sudo yunohost app upgrade jellyfin -F
```
