### ISSUE TITLE
unable to set parameters for opensubtitles plugin

### ISSUE THREAD

**Issue by russulae** [YunoHost-Apps/jellyfin_ynh#153]
Hi !

### Describe the bug

I don't remember being able to set up the opensubtitles plugin since I installed jellyfin on yunohost. when I ask for the parameters of that particular plugin in Dashboard>Plugins they are not displayed right, the form is either behind the plugins buttons or in front of them.

![jellyfin-plugin-settings-1](https://github.com/YunoHost-Apps/jellyfin_ynh/assets/77500880/7d6a442b-98c7-4aa0-818c-32f7b1ed3642)
![jellyfin-plugin-settings-2](https://github.com/YunoHost-Apps/jellyfin_ynh/assets/77500880/6127ba62-2832-434f-8c86-acd2a517f77e)

 in either cases the `back` and `home` buttons on the page don't work. If I reload the page, the form is displayed but filling it and clicking on the `save` button only reload the page and show an empty form again.

![jellyfin-plugin-settings-3](https://github.com/YunoHost-Apps/jellyfin_ynh/assets/77500880/e29db714-965d-4646-9ca0-457240e47502)

### Context

- Hardware:  Old laptop
- YunoHost version: 11.2.11.3 (stable).
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: jellyfin Version : 10.8.13, opensubtitles plugin 19.0.0.0

### Steps to reproduce

   1. log in jellyfin wit an admin account
   2. go to the DashBoard
   3. go to the 'Plugin' tab
   4. click on the Open Subtitles plugin button or on the three dots buttons
   5. face your screen with dismay.
  

### Expected behavior

the plugin's setting form is correctly displayed and whatever credential you fill in is used by the plugin to get the subtitles

### Logs

there is nothing relevant in jellyfin's logs, but the browser console is yelling that :
```
Loading failed for the module with source “blob:https://jellyfin.[mydomain.com]/824c666a-564d-4ca2-a75b-12168c01354f”. [index.html:1:1](https://jellyfin.[mydomain.com]/web/index.html#!/configurationpage?name=opensubtitles)
Content-Security-Policy: The page’s settings blocked a script (script-src-elem) at blob:https://jellyfin.[mydomain.com]/824c666a-564d-4ca2-a75b-12168c01354f from being executed because it violates the following directive: “script-src https: data: 'unsafe-inline' 'unsafe-eval'” [main.jellyfin.bundle.js:2:254778](https://jellyfin.[mydomain.com]/web/main.jellyfin.bundle.js?d5f64bca077b6d6aaf33)
Uncaught (in promise) Error: Failed to import: https://jellyfin.[mydomain.com]/web/configurationpage?name=opensubtitlesjs
    onerror https://jellyfin.[mydomain.com]/web/main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2
[main.jellyfin.bundle.js:2:254433](https://jellyfin.[mydomain.com]/web/main.jellyfin.bundle.js?d5f64bca077b6d6aaf33)
```
note that I recently had an issue with another app (galène), that was blocked by nginx's content security policy, I had to edit `security.conf.inc` manually and add  `connect-src ws: wss: 'self';` to the `more_set_headers "Content-Security-Policy : […]` line (see https://forum.yunohost.org/t/galene-couldnt-connect-to-wss/29196/6 for more details)

**Comment by russulae** [comment]
I maybe should have checked upstream first : https://github.com/jellyfin/jellyfin-plugin-opensubtitles/issues/131 apparently it will be fixed in jellyfin 10.9.0 due to be release soon, therefore I close this ticket, sorry for the noise.

**Comment by Halhadus** [comment]
Hello. Sorry for commenting on an old Issue but I didn't want it to be a duplicate. I have exactly the same problem with other (all) plugins. I tried writing the configuration file manually but it still doesn't read it. If I have a log to share I can share it. Thanks. Using latest version.

**Comment by russulae** [comment]
Hi @Halhadus !
I had some file system errors that prevented the system to boot recently, and after a few weeks offline, checking/repairing the filesystem and upgrading everything that went out-of-date during that time (including jellyfin),  my problem  (and some other little glitches) is now solved, it was probably caused by a faulty hardware  — even if everything works now,  I don't trust that disk anymore, so I'm getting ready to switch to newer hardware anyway…

**Comment by Halhadus** [comment]
> Hi [@Halhadus](https://github.com/Halhadus) ! I had some file system errors that prevented the system to boot recently, and after a few weeks offline, checking/repairing the filesystem and upgrading everything that went out-of-date during that time (including jellyfin), my problem (and some other little glitches) is now solved, it was probably caused by a faulty hardware — even if everything works now, I don't trust that disk anymore, so I'm getting ready to switch to newer hardware anyway…

Oh I'm sorry to hear that. I hope you don't experience this situation again. So should I just wait?
