### ISSUE TITLE
Jellyfin fails to upgrade after Bookworm migration

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/jellyfin_ynh#163]
### Describe the bug

After upgrading my RPi4 to YNH 12 beta test, upgrading Jellyfin fails during package upgrade: the upgrade script tries to downgrade ffmpeg6, which is not allowed.
Subsequently, the restore script fails due to changed URL (fixed by https://github.com/YunoHost-Apps/jellyfin_ynh/pull/162). I will simply reinstall the app from scratch. 

### Logs

https://paste.yunohost.org/raw/owedigozow

**Comment by Salamandar** [comment]
Yes, should be fixed by #164.

**Comment by Salamandar** [comment]
Actually… not fixed…

**Comment by Salamandar** [comment]
Fixed now.
