### ISSUE TITLE
How to add the subdomain public

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/jellyfin_ynh#169]
Hello, 

i install the latest version jelyfin on my yunohsot and works fine

the only problem i got i have to connect on yunohost interface and jellyfin interface

that's means,  i can't use android application, or i have to connect two times before access it

how to make jellyfin with the subdomain totaly free of yunohost, to access it ?

**Comment by Salamandar** [comment]
You just have to set jellyfin as public.
Go into your admin panel -> accounts -> manage groups and permissions and in the "visitors" section, "Add permission" and select Jellyfin.

**Comment by tituspijean** [comment]
Considering this to be solved. Feel free to reopen if needed.
