### ISSUE TITLE
Failed to update, restore and install Jellyfin

### ISSUE THREAD

**Issue by retiolus** [YunoHost-Apps/jellyfin_ynh#177]
I tried to update Jellyfin to latest version, it failed: https://paste.yunohost.org/raw/ahodulozoz

I tried to restore the backup, it failed: https://paste.yunohost.org/raw/uhevupiyoq

Now I try to install last version, it fails: https://paste.yunohost.org/raw/uhonuzusex

**Comment by kay0u** [comment]
Should be fixed by #179
