### ISSUE TITLE
Cant install Jellyfin: The operation 'Install the 'jellyfin' app' could not be completed

### ISSUE THREAD

**Issue by planecore** [YunoHost-Apps/jellyfin_ynh#23]
Error: The operation 'Install the 'jellyfin' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20200623-100629-app_install-jellyfin --share' to get help

The full log: https://paste.yunohost.org/raw/iludomuqac

**Comment by liberodark** [comment]
Thanks for your report after try to install manually just run dpkg reconfigure -a
After that the install work try this and tell me
