### ISSUE TITLE
CI fails because of 500 errors (but it shouldn't)

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/jellyfin_ynh#24]
I installed Jellyfin on my own server (Stretch), and I too have thosc 500 errors. 10 seconds later, Jellyfin runs fine.
It looks like either :
* Jellyfin shows a 500 error even if it reported it started (should be fixed upstream)
* The systemd unit isn't implemented correctly (it should wait for Jellyfin to be fully started)

Either way, the CI fails but a workaround should be found.

**Comment by liberodark** [comment]
dont have this error.
systemd service is installed by jellyfin not by me

**Comment by Salamandar** [comment]
What I meant is that CI shows those errors, so Jellyfin is considered as "broken".
https://ci-apps.yunohost.org/ci/job/1181
Search "502" in the web page.

**Comment by liberodark** [comment]
Yeah but is not broken the CI of yunohost is broken somes apps.
