### ISSUE TITLE
Missing meta package?

### ISSUE THREAD

**Issue by mdic** [YunoHost-Apps/jellyfin_ynh#28]
I was about to create a pull request for this repo to support Jellyfin's latest version, then found that the update had already been included. However, I did not see in the `conf` folder the `src` file for the meta package [jellyfin_10.6.1-1_all.deb](https://repo.jellyfin.org/releases/server/debian/versions/stable/meta/10.6.1/). I'm not sure whether this is needed; in the script I had modified I included it.

**Comment by liberodark** [comment]
Not need but yes now jellyfin is in 10.6.2.
