### ISSUE TITLE
Stabality of this package

### ISSUE THREAD

**Issue by SimonMellerin** [YunoHost-Apps/jellyfin_ynh#37]
Hi,

On this page https://yunohost.org/#/apps I can see that jellyfin_ynh is in a 'not working' state, but in the readme of this repo, there's no information about it ?

So how stable is this package ? Can you add this info in the readme ?

Thanks
Simon

**Comment by liberodark** [comment]
Is stable.

**Comment by SimonMellerin** [comment]
ok thanks
