### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/jellyfin_ynh#4]
Does this package support LDAP ?

If not, do you think it could be possible using the official ldap plugin ?

https://github.com/jellyfin/jellyfin-plugin-ldapauth

---

I'm currently using jellyfin in docker and tried some ldap config but I failed.

Also I'll be glad to migrate to this package (even without ldap), do you know how to migrate the db, config and all ?

**Comment by gnouts** [comment]
FTR, I managed to authenticate users from LDAP within Jellyfin in docker. The issue was more docker than ldap actually, as yunohost firewall blocked port 389 from docker internal network.

 Anyway, here is my ldap settings : 
![Capture d’écran du 2019-10-11 19-10-31](https://user-images.githubusercontent.com/17988185/66670768-d36f2880-ec5a-11e9-80b4-704386ea09bb.png)

Also `Enable User creation` is checked.
I used my lan ip as host because of docker but you should probably use localhost. You could also use `uid` instead of `uidNumber` for admin filter, picked from a list at installation like other app do

**Comment by liberodark** [comment]
fixed

**Comment by MayeulC** [comment]
Hey, since this is fixed, would you mind adjusting the readme? I got the impression this wasn't supported, so I passed on the yunohost package :/

> Multi-user support
>
>   Are LDAP and HTTP auth supported? No

Thanks in advance,
