### ISSUE TITLE
CI test fail

### ISSUE THREAD

**Issue by liberodark** [YunoHost-Apps/jellyfin_ynh#46]
> Issue: Don't Touch Master or Testing without Ask.

> Commit: Revert "Testing (#39)"

I'm sorry, but you can't do that. Especially without providing any reason, any logs, and just saying "this work broke the APP
and you CI dont make all tests". Before this PR the app was uninstallable.

The right way to deal with a problem is : 
- Create an issue, explain your problem.
- Create a new PR, explain how/why the problem is solved.

The CI may not be perfect, but when it say "ynh_add_nginx_config is now an official helper since version '2.7.2'", there is probably a reason. When the install fails with 
```
Warning: yunohost.hook <lambda> - [1482.1] E: Packages need to be removed but remove is disabled.
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libass5' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libbluray1' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libva-drm1' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libva-x11-1' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libva1' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libx264-148' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libx265-95' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libwebpmux2' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] Unable to install dependencies
```
It's probably not a false positive error.

**Comment by liberodark** [comment]
I think CI is not test last PR @kay0u 
Your issue is Debian 9 apps : 
libbluray1
libva-drm1
libva-x11-1
libva1
libx264-148
libx265-95

Can resend a test on master ?

**Comment by kay0u** [comment]
With latest test (before the revert drama), everything was green: https://ci-apps.yunohost.org/ci/job/2052 No more warnings about deprecated use of helpers, no more installation problems.

The next test will come later: https://ci-apps.yunohost.org/ci/

**Comment by liberodark** [comment]
Yes normaly now all is green too now.
Need to wait next test.

**Comment by alexAubin** [comment]
Last warning by the way : [as explained in the other issue](https://github.com/YunoHost-Apps/jellyfin_ynh/issues/41#issuecomment-729392710), the app is still miserably failing during install as demonstrated [here](https://ci-apps-dev.yunohost.org/jenkins/job/jellyfin_ynh%20liberodark%20(tituspijean)/lastBuild/console).

This should be confirmed by a test on the "real" CI in just a few hours : https://ci-apps.yunohost.org/ci/job/83

After which if things are still broken, I plan to rework the commit history to restore the original work of Eric & Titus as explained in the aforementioned comment

**Comment by alexAubin** [comment]
So yup, test failed.

```
Warning: yunohost.hook <lambda> - [1595.1] dpkg: dependency problems prevent configuration of jellyfin-ffmpeg:
Warning: yunohost.hook <lambda> - [1595.1]  jellyfin-ffmpeg depends on libwebpmux3 (>= 0.6.1-2); however:
Warning: yunohost.hook <lambda> - [1595.1]   Package libwebpmux3 is not installed.
Warning: yunohost.hook <lambda> - [1595.1] dpkg: error processing package jellyfin-ffmpeg (--install):
Warning: yunohost.hook <lambda> - [1595.1]  dependency problems - leaving unconfigured
Warning: yunohost.hook <lambda> - [1595.1] Errors were encountered while processing:
Warning: yunohost.hook <lambda> - [1595.1]  jellyfin-ffmpeg
Error: yunohost.app app_install - [1595.1] Could not install jellyfin: An error occurred inside the app installation script
```

 I removed the whole commit apocalypse of the last few days and we're back to same state than 9ish days ago, which should fix the CI. Feel free to open an issue / PR with some actual details on your claim of the app being "broken".

![4ng7z7](https://user-images.githubusercontent.com/4533074/99917874-7970db80-2d13-11eb-8d51-bbb87e59013c.jpg)
