### ISSUE TITLE
Official Repo key is expiring. Need update.

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/jellyfin_ynh#47]
Not sure but maybe this is something that need to be integrated in the next update :

From Jellyfin staff on reddit :
> Our GPG key for signing our Debian and Ubuntu repositories (https://repo.jellyfin.org/debian and https://repo.jellyfin.org/ubuntu) is set to expire next month.
> Unfortunately this was an oversight when we first set up this repo, and we never provided any convenient way to update this. As a remedy, we've removed the expiry on the key and put a new version on the repo. You will need to manually replace the old key with the new one.

https://www.reddit.com/r/jellyfin/comments/jz6u9o/debian_ubuntu_repo_users_our_key_is_expiring/

**Comment by tituspijean** [comment]
Thanks for the notification. It should be OK, though.

When we add packages from external repos, the source is then removed to avoid unwanted and potentially breaking updates. So every time we want to install or upgrade the app, the key is downloaded again.

The magic happens [over there](https://github.com/YunoHost-Apps/jellyfin_ynh/blob/0a7bc4d1f26777f096e7280bda5f46744af6508b/scripts/install#L71).

**Comment by tituspijean** [comment]
I am closing this issue, but still setting a reminder to test the app installation on 2020-12-15, *just to be sure*.

**Comment by tituspijean** [comment]
Installation is working alright on my end. 😉
