### ISSUE TITLE
Upgrade 10.6.4 to 10.6.4-ynh1 fails

### ISSUE THREAD

**Issue by lentemoore** [YunoHost-Apps/jellyfin_ynh#48]
Hi, as the titel says, the upgrade fails. Apparently the backup doesn't work. Here is the relevant log output:

```
WARNING - 7115 Could not back up jellyfin
WARNING - Traceback (most recent call last):
WARNING -   File "/usr/lib/moulinette/yunohost/backup.py", line 710, in _collect_app_files
WARNING -     raise_on_error=True, chdir=tmp_app_bkp_dir, env=env_dict)[0]
WARNING -   File "/usr/lib/moulinette/yunohost/hook.py", line 347, in hook_exec
WARNING -     raise YunohostError('hook_exec_failed', path=path)
WARNING - YunohostError: Could not run script: /tmp/backup_eD93E1
WARNING - 7121 Nothing to save
DEBUG - + '[' 1 -eq 0 ']'
WARNING - Backup failed, the upgrade process was aborted.
DEBUG - + ynh_die '--message=Backup failed, the upgrade process was aborted.'
DEBUG - + ret_code=1
DEBUG - + echo 'Backup failed, the upgrade process was aborted.'
DEBUG - + exit 1
2020-11-24 16:32:59,133: ERROR - Could not upgrade jellyfin: An error occurred inside the app upgrade script
```

**Comment by alexAubin** [comment]
Can you share the full log of the upgrade

![4m8yjzç](https://user-images.githubusercontent.com/4533074/100246410-63446480-2f39-11eb-9a17-d83ab4b9ad22.jpg)

**Comment by lentemoore** [comment]
Sorry, here you go: https://paste.yunohost.org/raw/mikidulape

**Comment by alexAubin** [comment]
So yeah I suppose that's probably "expected" that it doesn't work because before the merge of the work a few days ago, the app was flagged as level 0 / notworking and Yunohost should have discouraged you from installing it (and not sure to understand how you got it working in the first place) ... Anyway, I guess the issue sounds kinda simple and you should be able to work around it by running : 

```
touch /etc/systemd/system/jellyfin.service
```

which should make the pre-upgrade safety-backup happy

**Comment by lentemoore** [comment]
I installed it sometime last year I think, so it's been a while (with several hiccups along the way ^^).

If I touch the file, the upgrade fails again at the same stage, different error: https://paste.yunohost.org/raw/wapaxapeva
If I umask jellyfin.service again, the service file gets deleted again and we're back to the start: https://paste.yunohost.org/raw/olamodajih

I'd just reinstall, but there are some non-persistent database changes I'd like to keep...but that is an option.

**Comment by alexAubin** [comment]
hmpf I guess you can disable the backup and run the upgrade in cli with (as root:)

```
NO_BACKUP_UPGRADE=1 yunohost app upgrade jellyfin
```

**Comment by lentemoore** [comment]
Thanks for the help, that worked.
