### ISSUE TITLE
Jellyfin can't find chromecast device to stream to

### ISSUE THREAD

**Issue by brunovianna** [YunoHost-Apps/jellyfin_ynh#53]
Hi

I have a chromecast and use it to stream videos from varied sources. When I try to stream something hosted on my jellyfin, it won't find the chromecast device. I think it is related to this issue: https://github.com/jellyfin/jellyfin/issues/3852
So it might be just a question of upgrading to the latest version of Jellyfin?

Iḿ running a raspi4 with my own DNS. Versions:

Jellyfin 10.6.4~ynh3

yunohost: 
  repo: stable
  version: 4.1.7.1
yunohost-admin: 
  repo: stable
  version: 4.1.4
moulinette: 
  repo: stable
  version: 4.1.4
ssowat: 
  repo: stable
  version: 4.1.3

**Comment by Salamandar** [comment]
@brunovianna This app is on 10.7.0. Did it solve your problem ?

**Comment by MX10-AC2N** [comment]
Hi I have a bit of the same problem with my Harman Kardon amp, and I solve the problem in CLI with the command "sudo yunohost firewall allow UDP 1900" after that my amp and my tv are visible from the Jellyfin interface ..
The only problem is that you have to re-type the command at each start, I think it is more of a problem of Jellyfin which has not yet fully developed for the upnp / dlna ..
Hope this fixes your problem, good luck.

**Comment by brunovianna** [comment]
Hello, I was finally able to test this again with version 10.7.6~ynh1 . It works perfectly with chromecast now. I'm closing the issue.
