### ISSUE TITLE
Unable to install plugins on stock installation

### ISSUE THREAD

**Issue by navanchauhan** [YunoHost-Apps/jellyfin_ynh#54]
I was unable to install any plugin until I manually created the folder and used `chown` to give permission to the `jellyfin` user group. Maybe, consider creating the plugins folder at `/var/lib/jellyfi` as path of the install script?

**Comment by tituspijean** [comment]
This should be resolved when the PR referenced above is merged: since the new version comes with one plugin, the directory should be here.
