### ISSUE TITLE
Do not restore on ynh rasberry pi

### ISSUE THREAD

**Issue by stevenmache** [YunoHost-Apps/jellyfin_ynh#58]
Hi,

Many thanks for putting Jellyfin on ynh ! Everything works and the app + mobile app are brillant ! 

I guess it is still in early packadging, but just to let you know, I tested a restore on Jellyfin. 
You'll find the details in the topic is posted here : https://forum.yunohost.org/t/restore-of-jellyfin-failed/14921/2
Or
https://paste.yunohost.org/raw/turevugiru

Thanks

**Comment by tituspijean** [comment]
Duplicate #56
