### ISSUE TITLE
Jellyfin Port isn't changed if none-default port is chosen.

### ISSUE THREAD

**Issue by lentemoore** [YunoHost-Apps/jellyfin_ynh#6]
When installing on a system where port 8096 is blocked, the script only changes the nginx confs port, not the jellyfin port in system.xml.

**Comment by liberodark** [comment]
Need to close ?

**Comment by lentemoore** [comment]
Unless @tituspijean's changes are merged here, the issue remains open.

**Comment by liberodark** [comment]
merged
