### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by pagiraud** [YunoHost-Apps/jellyfin_ynh#60]
### Describe the bug
This morning, an upgrade to Jellyfin 10.7 popped up when I checked for upgrades of my Yunohost. I accepted it. The upgrade failed and Jellyfin 10.6.4 is uninstalled: I can’t access my movies and musics anymore.

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.1.7.4
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: Jellilfyn 10.7

### Steps to reproduce

- *If you used the webadmin, please perform the equivalent command from the CLI first.*
- *If the error occurs in your browser, explain what you did:*
   1. Go to 'Mettre à jour le système'
   2. Click on 'Mettre à jour' at the right of "Jellyfin jellyfin de 10.6.4~ynh3 à 10.7.0~ynh1"

### Expected behavior

The upgrade succeeds.

### Logs
[Logs](https://paste.yunohost.org/raw/qepawaloju)

**Comment by tituspijean** [comment]
@ericgaspar should we revert the merge? I have no time right now how to fix this, and restores will continue to fail since 10.6.4 is not available anymore. Should we revert back to deb sources?

**Comment by Tigui14** [comment]
I've hit the same problem on my server, though in my case Jellyfin was not totally uninstalled, but the restoration was not functional either. I had to manually add /etc/jellyfin/logging.json (copied from the repos) and make the user jellyfin the owner of the directories /var/log/jellyfin/ and /var/cache/jellyfin. On the first successful start, I also had to go through the whole initial configuration again as the /etc/jellyfin/system.xml was not part of the restoration (but my libraries were still configured, and all my data seem to be recovered)

**Comment by pagiraud** [comment]
With the new version of the package (ending with ynh2), the upgrade apparently succeeds but I get an error 502 Bad Gateway when trying to access Jellyfin. I open a new bug for that.
