### ISSUE TITLE
No Administrator permission with LDAP

### ISSUE THREAD

**Issue by h3ndrik** [YunoHost-Apps/jellyfin_ynh#61]
I did a clean install of the very recent version 10.7.0~ynh1 with LDAP
and selected some user as Administrator.

On first login as the administrator user, the admin menu is missing.
Jellyfin seems not to recognize the admin permissions.

The `LdapAdminFilter` in the LDAP configuration seems to be correct.

This could be a bug in the ldapauth-plugin. I found this:
https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/55

I tried another clean install and enabled the StartupWizard in `/etc/jellyfin/system.xml`, disabled the LDAP-plugin by moving it out of the directory, and did the setup manually. This works as intended and the admin permission is kept even after re-enabling the LDAP-plugin.

**EDIT**: Could also be related to my setup. I've tested too many things in the past days. If this is working fine for other people, i'd be happy to close this issue.

**Comment by tituspijean** [comment]
Closing since this issue is old. If this is not fixed in newest versions, do not hesitate to open it again.
