### ISSUE TITLE
Impossible to access Jellyfin (error 502) after upgrade to 10.7.0

### ISSUE THREAD

**Issue by pagiraud** [YunoHost-Apps/jellyfin_ynh#67]
After a failed upgrade to Jellyfin 10.7.0~ynh1 that uninstalled the app, I managed to make it work again with a pre-upgrade backup. Within Jellyfin, it was said to be the 10.7.0 version. From the admin panel, it was said to be the 10.6.4 version, so the upgrade to Jellyfin 10.7.0~ynh1 kept showing up. Today, I have seen that it was possible to upgrade to Jellyfin 10.7.0~ynh2.

### Describe the bug

I upgraded to 10.7.0~ynh2. The upgrade succeeded but now Jellyfin can’t be accessed (502 Bad Gateway).

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4:1:7:4
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: Jellyfin 10.7.0~ynh2
- If upgrading, current package version: 10.7.0~ynh2

### Steps to reproduce
I just upgraded the app from the webadmin.

### Expected behavior
After a successful upgrade, the app works.

### Logs

https://paste.yunohost.org/raw/ukicaxabej

**Comment by artus40** [comment]
Same problem here. Upgrade was successfull too.

An error shows up in log (systemctl -u jellyfin) after trying to access the app. I pasted the (seemingly) interesting bit here : https://paste.yunohost.org/qucidurabo.md
