### ISSUE TITLE
Jellyfin no longer installable on latest YNH

### ISSUE THREAD

**Issue by studio315b** [YunoHost-Apps/jellyfin_ynh#68]
### Describe the bug

When attempting to install jellyfin during the YNH install script, it attempts to install 3 packages `jellyfin`, `(=`, `1.7.0)` instead of installing `jellyfin (= 1.7.0)` this causes the installer to fail.

### Context

- Hardware: personal machine (quad-core x64 w/ 4gb ram)
- YunoHost version: 4.1.7.4
- I have access to my server: Direct Access
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 1.7.0~ynh2

### Steps to reproduce

`yunohost app install jellyfin --debug`

### Expected behavior

Jellyfin successfully installs

### Logs

https://paste.yunohost.org/raw/edupabemid

**Comment by MX10-AC2N** [comment]
Same failed install.. 
https://paste.yunohost.org/raw/marameduhe
How can install jellyfin on yunohost ??

**Comment by qeved** [comment]
Hi, Any update please ? I really want to use again jellyfin which is amazing ! Thanks for all in advance

**Comment by MX10-AC2N** [comment]
Hi everyone, can we have some info? I am waiting to be able to install jellyfin on my yunohost server, but maybe I have to turn to other apps ..? Jellyfin remains the best solution for me, (music, video, broadcast on my amp or on my TV it's just great ..)
Hope you find a solution ..
