### ISSUE TITLE
Fresh install doesn't redirect to jellyfin from yunohost/sso

### ISSUE THREAD

**Issue by lentemoore** [YunoHost-Apps/jellyfin_ynh#7]
After a fresh install, clicking the Jellyfin icon in the user access screen doesn't redirect to jellyfin, I have to type /web/index.html at the end of the url by hand for it to work.

**Comment by liberodark** [comment]
Need to close ?

**Comment by lentemoore** [comment]
Unless @tituspijean's changes are merged here, the issue remains open.

**Comment by liberodark** [comment]
is all closed... if you want to make PR no problem but dont break app

**Comment by liberodark** [comment]
mer
