### ISSUE TITLE
Impossible to install: dependecies issue

### ISSUE THREAD

**Issue by mateMathieu** [YunoHost-Apps/jellyfin_ynh#70]
### Describe the bug

Freshly installed x86 system. Other apps installed like discourse (unofficial).

### Context

- Hardware: x86 computer with RAID(hw)
- YunoHost version: 4.1.8
- I have access to my server through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No.
- trying to install package version/branch: 10.7.0

### Steps to reproduce

- Clicked on "Install with Yunohost",
- Failed to install dependencies
- tried via CLI,
- dump available here: https://paste.yunohost.org/raw/pinogihepa

### Expected behavior
Congraz, Jellyfin is installed!

### Extracts from the Logs (https://paste.yunohost.org/raw/pinogihepa)

32283 WARNING E: Packages need to be removed but remove is disabled.
32283 DEBUG   jellyfin-ynh-deps
32283 DEBUG 0 upgraded, 0 newly installed, 1 to remove and 25 not upgraded.
32284 DEBUG ++ cat /tmp/tmp.xXXeBfSnt2/dpkg_log
32284 DEBUG ++ grep -oP '(?<=-ynh-deps depends on ).*(?=; however)'
32284 DEBUG ++ tr '\n' ' '
32284 DEBUG + local 'problematic_dependencies=jellyfin (= 10.7.0-1) '
32284 DEBUG + [[ -n jellyfin (= 10.7.0-1)  ]]
32284 DEBUG + ynh_package_install jellyfin '(=' '10.7.0-1)' --dry-run
32284 DEBUG + ynh_apt --no-remove --option Dpkg::Options::=--force-confdef --option Dpkg::Options::=--force-confold install jellyfin '(=' '10.7.0-1)' --dry-run
32284 DEBUG + ynh_wait_dpkg_free
32284 DEBUG + local try
32284 DEBUG + set +o xtrace
32284 DEBUG + sed --quiet '/Reading state info/,$p'
32284 DEBUG + grep -v 'fix-broken\|Reading state info'
32385 DEBUG + return 0
32385 DEBUG + LC_ALL=C
32385 DEBUG + DEBIAN_FRONTEND=noninteractive
32385 DEBUG + apt-get --assume-yes --quiet -o=Acquire::Retries=3 -o=Dpkg::Use-Pty=0 --no-remove --option Dpkg::Options::=--force-confdef --option Dpkg::Options::=--force-confold install jellyfin '(=' '10.7.0-1)' --dry-run
32686 DEBUG + ynh_die '--message=Unable to install dependencies'
32686 WARNING E: Unable to locate package (
32687 DEBUG + local legacy_args=mc
32687 WARNING E: Unable to locate package 10.7.0-1)
32687 DEBUG + args_array=([m]=message= [c]=ret_code=)
32688 WARNING E: Couldn't find any package by glob '10.7.0-1)'
32688 DEBUG + local -A args_array
32688 WARNING E: Couldn't find any package by regex '10.7.0-1)'
32688 DEBUG + local message
32688 WARNING Unable to install dependencies

**Comment by mateMathieu** [comment]
Hope it helps  :)

**Comment by tituspijean** [comment]
Hiya! This has been pretty much covered in all the recent issues and on the forum. If you are feeling adventurous, you can try to install the fix with 

```
yunohost app install https://github.com/YunoHost-Apps/jellyfin_ynh/tree/fix-restore --force
```

I would *love* feedback.
