### ISSUE TITLE
Automated server address in web interface fails

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/jellyfin_ynh#76]
### Describe the bug

In some instances, the server is detected and listed in the web interface, but connection fails anyway. One has to remove the server and input its address again.

### Context

 Jellyfin v10.7.5

**Comment by Salamandar** [comment]
Reproduced on my server. I'm wondering if this is some browser-side cache that was not invalidated ?

**Comment by tituspijean** [comment]
It could be, I usually have to delete my cache and cookies when I try to install it multiple times in the same session. I will try deleting them too next time I test the app.

**Comment by pagiraud** [comment]
This problem also occurs when using the Jellyfin app in Android (at least the F-Droid build), not only from a browser.

**Comment by JoshuaRL** [comment]
I'm seeing this issue as well.

**Comment by tituspijean** [comment]
I know it is tempting to comment to bump the issue up or ping me to get a faster resolution, but "+1" are more welcomed with the thumbs up (as you already did). :)

Concerning the issue, I have no idea what it is nor or how it happens. :(

**Comment by Salamandar** [comment]
FYI After a full server install with the testing branch, the issue did not show up. Maybe there was an upstream bug that was fixed ? I think I saw one on their github bug tracker.
