### ISSUE TITLE
Cannot Access Admin Settings

### ISSUE THREAD

**Issue by JoshuaRL** [YunoHost-Apps/jellyfin_ynh#78]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to Jellyfin itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

I am having the same issue as #[Issue #76](https://github.com/YunoHost-Apps/jellyfin_ynh/issues/76) but even after connecting with the site.tld/jellyfin URL, I can't get access to any Admin settings. 

### Context

- Hardware: VPS
- YunoHost version: 4.2.6 stable
- I have access to my server: Through SSH and through the webadmin
- I did no special tweaking
- Using, or trying to install package version/branch: 10.7.5~ynh1

### Steps to reproduce

- Install Jellyfin fresh from webadmin
- Manually connect to server using site.tld/jellyfin or linked from site.tld Yunohost homepage
- No admin options are available despite being signed in using assigned admin account upon install
- Tried logging in as another account, or site.tld/jellyfin/admin, no changes

### Expected behavior

Should have access to admin settings to add, edit, and scan libraries

### Logs

No logs I can find

**Comment by JoshuaRL** [comment]
Here is a picture of what I see when I log in as the admin account listed on install
![JellyfinEmpty](https://user-images.githubusercontent.com/11461270/122268501-c11ea680-cea1-11eb-93ca-a580724ecfa8.png)

And here's the admin panel with site info redacted:
![JellyfinSettings](https://user-images.githubusercontent.com/11461270/122268613-e6abb000-cea1-11eb-999b-bc53d000b083.png)

**Comment by jlopez777** [comment]
@JoshuaRL , I had issues as well. But once I changed "admin" field to my primary user name I was able to access. Let me know if that fixes it for you like it did for me. 

I did notice it isn't as fast as I once remember it when it was working before...so if it does work, let me know if you notice a performance downgrade.

**Comment by Salamandar** [comment]
@JoshuaRL Do you still have the issue ? The screenshot only shows there's no library yet, you should have a side panel where you can access the admin panel and add content libraries.

**Comment by Salamandar** [comment]
Let's close it as we don't have any answer for almost a year.
