### ISSUE TITLE
Rework sources retrieval

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/jellyfin_ynh#81]
### Describe the bug

Whenever a new version is released upstream, older sources get often removed:
1. it forces us to update this package ASAP, otherwise new installs fail
2. it prevents us from testing upgrades from version to another

### Context

All versions, all installation/upgrade modes.

### Objective

- Review the way we pull sources and install deb packages

**Comment by tr1p0p** [comment]
I guess it force to use https://repo.jellyfin.org/archive/debian/stable/ and just have the .deb package, right ?

**Comment by tituspijean** [comment]
Yes, kayou has made a big step forward with #84. It needs some fine-tuning for ARM/ARM64 though, and weirdly I end up with one issue already reported in the past on the forum with failing journal database migration.

**Comment by tr1p0p** [comment]
Ok i see, jellyfin have a weird way of put release and source, like why not using a git ? I'm on RPI 4 too so i can help for testing stuffs and all.

Thks for the work, despite all this jellyfin seem to be the greatest open-source media streaming solution around here, i hope it get back in good shape on the yunohost catalog :pray:
