### ISSUE TITLE
Raspberry Pi 4 - video buffering

### ISSUE THREAD

**Issue by xander-p** [YunoHost-Apps/jellyfin_ynh#85]
Hi folks,

Many thanks for bringing this app to YunoHost. I have it installed on my Raspberry Pi 4. When a video is streamed, I experience buffering every few seconds. If I wait a few minutes, then the video plays just fine, until it "catches up" the buffering line. 

Here is my log:
https://pastebin.com/fGgXchYb
Now, in the end, there are lines like:
frame=   57 fps= 33 q=-0.0 size=N/A time=00:00:01.19 bitrate=N/A dup=28 drop=0 speed=0.698x  
If I understand correctly, speed <1 will always result in buffering. 

Here are my Jellyfin transcoding settings:
![image](https://user-images.githubusercontent.com/32178155/146372107-594c72d5-f010-4583-8be0-c23f073c853f.png)

Could anyone please take a look at what I might set up wrong? (I don't have much of prior experience with ffmpeg and video transcoding).

**Comment by xmgz** [comment]
hi, V4L2 setting is recommended in [jellyfin docs](https://jellyfin.org/docs/general/administration/hardware-acceleration.html) for rasPi 

you can test if it makes any diference.

**Comment by Salamandar** [comment]
Hi @xander-p , you should contact the Jellyfin folks here : https://forum.jellyfin.org.
This is not the repository of Jellyfin but for the packaging scripts for Yunohost :)

**Comment by tituspijean** [comment]
Most likely a configuration issue then, let's close here. Feel free to reopen if needed.
