### ISSUE TITLE
Package Installation Broken on Buster

### ISSUE THREAD

**Issue by navanchauhan** [YunoHost-Apps/jellyfin_ynh#96]
404 on https://repo.jellyfin.org/releases/server/debian/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-buster_arm64.deb

I don't understand why the Jellyfin maintainers' remove the older binaries. Will open a PR soon to bump ffmpeg to 4.4.1-4

**Comment by Salamandar** [comment]
Should be fixed by #92.
